apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maria-pvc
spec:
  storageClassName: new-test
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: maria-pod
spec:
  containers:
    - name: database
      image: mariadb
      env:
      - name: MARIADB_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
             name: mysecret
             key: MARIADB_ROOT_PASSWORD
      volumeMounts:
      - mountPath: "/var/lib/mysql"
        name: maria-vol
  volumes:
    - name: maria-vol
      persistentVolumeClaim:
        claimName: maria-pvc
