apiVersion: v1
kind: PersistentVolume
metadata:
  name: maria-pv
spec:
  storageClassName: new-test
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/new-maria"

