apiVersion: v1
kind: PersistentVolume
metadata:
  name: new-pv
spec:
  storageClassName: test
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/new-pv"

