apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: create-deploy
rules:
- apiGroups: ["apps"] 
  resources: ["deployments"]
  verbs: ["get", "watch", "create","delete", "list"]
